dataset_params:
  im_path: 'data/train/images'

diffusion_params:
  num_timesteps : 1000
  model: 'ddim'
  scheduler: 'cosine'

  s: 0.008
  p: 2

model_params:
  im_channels : 1
  im_size : 28
  down_channels : [32, 64, 128, 256]
  mid_channels : [256, 256, 128]
  down_sample : [True, True, False]
  time_emb_dim : 128
  num_down_layers : 2
  num_mid_layers : 2
  num_up_layers : 2
  num_heads : 4

train_params:
  task_name: 'default'
  batch_size: 64
  num_epochs: 10
  num_samples : 1
  num_grid_rows : 1
  lr: 0.0001
  ckpt_name: 'mnist_ddim_cosine_1000.pth'